{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "8d046b8e_668f45d2",
        "filename": "libutils/SharedBuffer_test.cpp",
        "patchSetId": 2
      },
      "lineNbr": 39,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2021-04-28T17:50:53Z",
      "side": 1,
      "message": "why `- 1`?",
      "range": {
        "startLine": 39,
        "startChar": 82,
        "endLine": 39,
        "endChar": 85
      },
      "revId": "128826ca0774c1d69f75055e98e50cab302b4d9b",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "4cde0c63_a725b1fc",
        "filename": "libutils/SharedBuffer_test.cpp",
        "patchSetId": 2
      },
      "lineNbr": 39,
      "author": {
        "id": 1120458
      },
      "writtenOn": "2021-04-28T17:51:52Z",
      "side": 1,
      "message": "so that it can succeed sometimes. L32 is testing the failure case. Probably, I should do this separately, since it\u0027s adding coverage and I\u0027m fixing the test (which still don\u0027t know why it started breaking??) but couldn\u0027t resist",
      "parentUuid": "8d046b8e_668f45d2",
      "range": {
        "startLine": 39,
        "startChar": 82,
        "endLine": 39,
        "endChar": 85
      },
      "revId": "128826ca0774c1d69f75055e98e50cab302b4d9b",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}