{
  "comments": [
    {
      "key": {
        "uuid": "04b861a5_13b082c5",
        "filename": "fastboot/usb_osx.c",
        "patchSetId": 4
      },
      "lineNbr": 300,
      "author": {
        "id": 1010055
      },
      "writtenOn": "2015-08-19T22:02:35Z",
      "side": 1,
      "message": "Not sure if this is an error or a normal return condition.",
      "range": {
        "startLine": 300,
        "startChar": 13,
        "endLine": 300,
        "endChar": 16
      },
      "revId": "1e717be9d099a73e5d08a5f063a6459a0a7eab95",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "a4fb1585_2da3bbfc",
        "filename": "fastboot/usb_osx.c",
        "patchSetId": 4
      },
      "lineNbr": 300,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2015-08-19T22:07:57Z",
      "side": 1,
      "message": "yeah, it does seem like this should be an error, but i think this is so the calling code keeps going and tries other USB devices. (but then why are the ones below errors?)",
      "parentUuid": "04b861a5_13b082c5",
      "range": {
        "startLine": 300,
        "startChar": 13,
        "endLine": 300,
        "endChar": 16
      },
      "revId": "1e717be9d099a73e5d08a5f063a6459a0a7eab95",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}