{
  "comments": [
    {
      "key": {
        "uuid": "4d0ab91e_e9226e64",
        "filename": "liblog/logd_reader.cpp",
        "patchSetId": 3
      },
      "lineNbr": 428,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2019-10-08T19:17:46Z",
      "side": 1,
      "message": "you\u0027re not assigning `errno \u003d 0` anywhere, so this seems invalid?\n\n(which makes me realize the same issue [indirectly] with L396.)",
      "range": {
        "startLine": 428,
        "startChar": 19,
        "endLine": 428,
        "endChar": 29
      },
      "revId": "27bb63b905e1ec5a7a618da8ef15c1c655a7900a",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "ffb02823_7449d448",
        "filename": "liblog/logd_reader.cpp",
        "patchSetId": 3
      },
      "lineNbr": 428,
      "author": {
        "id": 1064128
      },
      "writtenOn": "2019-10-08T19:24:38Z",
      "side": 1,
      "message": "I\u0027ll add that.  Is it strictly required though?  If recv() returns -1; it should always set errno, no?",
      "parentUuid": "4d0ab91e_e9226e64",
      "range": {
        "startLine": 428,
        "startChar": 19,
        "endLine": 428,
        "endChar": 29
      },
      "revId": "27bb63b905e1ec5a7a618da8ef15c1c655a7900a",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}