{
  "comments": [
    {
      "key": {
        "uuid": "8f1e757f_83ec7e4f",
        "filename": "libutils/include/utils/StrongPointer.h",
        "patchSetId": 4
      },
      "lineNbr": 188,
      "author": {
        "id": 1010103
      },
      "writtenOn": "2020-02-21T19:10:00Z",
      "side": 1,
      "message": "strictly speaking this needs a null check. If we\u0027re running with exceptions disabled and the allocation failed the `new T` will have returned nullptr.",
      "range": {
        "startLine": 188,
        "startChar": 4,
        "endLine": 188,
        "endChar": 20
      },
      "revId": "401d69aa946b68c3d58f46c1c12b1ef5533025a5",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "40b3d80c_eddf450e",
        "filename": "libutils/include/utils/StrongPointer.h",
        "patchSetId": 4
      },
      "lineNbr": 188,
      "author": {
        "id": 1120458
      },
      "writtenOn": "2020-02-21T21:19:55Z",
      "side": 1,
      "message": "Hmmm? -fno-exceptions replaces exception throws with aborts. I thought I would need to explicitly allocate w/ \u0027std::nothrow\u0027 to get this behavior.",
      "parentUuid": "8f1e757f_83ec7e4f",
      "range": {
        "startLine": 188,
        "startChar": 4,
        "endLine": 188,
        "endChar": 20
      },
      "revId": "401d69aa946b68c3d58f46c1c12b1ef5533025a5",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}