{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "2b2cce6d_73ccd142",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000205
      },
      "writtenOn": "2020-12-18T02:02:04Z",
      "side": 1,
      "message": "OK but we are just as likely to hit an error in storage_file_open",
      "revId": "436100e7d52907d34d0f90a6245bc96f2de1827b",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "bc354336_841ce9cd",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1000205
      },
      "writtenOn": "2020-12-18T02:05:08Z",
      "side": 1,
      "message": "The log in the bug you linked made it to:\n```\nstorageproxyd: exiting proxy loop with status (-1)\n```\nSo this change will have no impact on that bug.",
      "revId": "436100e7d52907d34d0f90a6245bc96f2de1827b",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}