{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "91a144b9_8aa51f7a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1052399
      },
      "writtenOn": "2021-02-22T21:06:54Z",
      "side": 1,
      "message": "failed suite/test-mapping-presubmit-large-retry_cloud-tf is unrelated and flacky\n",
      "revId": "84006f5ab18ef434b2da40853405d40d7982317b",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}