{
  "comments": [
    {
      "key": {
        "uuid": "904b5ab1_1fa9668d",
        "filename": "init/reboot.cpp",
        "patchSetId": 2
      },
      "lineNbr": 409,
      "author": {
        "id": 1013433
      },
      "writtenOn": "2017-04-12T23:13:02Z",
      "side": 0,
      "message": "Was this possible, vold was just started, I guess it could have shutdown by now, but would there be a case for that?",
      "revId": "e4e4777fc775447a0cc76c3b23c9920bd6b49631",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}