{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "76ac799d_83d86b22",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 4
      },
      "lineNbr": 0,
      "author": {
        "id": 1809421
      },
      "writtenOn": "2021-04-15T01:05:31Z",
      "side": 1,
      "message": "Turns out I was skipping over the reconnect and silently spamming the same connection. Works now.",
      "revId": "e54e8d4ebf54513ed478fe5818fa0cd3b722c792",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}